### PR TITLE
Sync with upstream

### PR DESCRIPTION
**Pull request by hsm207**
Sync with upstream to get facebook/duckling#646

### CODE REVIEW

**Review by wochinge — COMMENTED** [review]
Seems good 👍🏻 Did you try building the Docker image locally to see if it still works with Rasa Open Source ?

**Comment by wochinge** [comment]
And do you any clue why all the checks are failing?

**Comment by hsm207** [comment]
> Seems good 👍🏻 Did you try building the Docker image locally to see if it still works with Rasa Open Source ?

@wochinge yes. I built this image locally and connected a bot to it. The entity extraction using Duckling still works.

> And do you any clue why all the checks are failing?

The last check (`windows-latest / ghc 9.0.1`) has error compiling `HsOpenSSL`:

image

Scrolling up to see the error:

image

Seems like it is missing some dependencies.

But on upstream, the build passes.

The other checks did not fail. They were just cancelled.  This is because all jobs were defined using a matrix and if one job fails the rest are stopped.

**Comment by wochinge** [comment]
Let's try re-running them. The tests seem to pass in the upstream repo so they should also pass here.

**Comment by hsm207** [comment]
I reran it a few times yesterday and it always failed at the same spot. Let's see how it goes today....

**Comment by hsm207** [comment]
it still fails.

Since we are deploying in a linux container. Would it be okay to remove the check for windows and see if that fixes it?

**Comment by wochinge** [comment]
Seems their last run is also ages ago. Can we do one last thing before merging this? Can you please create a new fork of duckling and see whether the tests pass their? If they also fail there, then it's fine to merge this PR in my opinion.

**Comment by wochinge** [comment]
(since I've been working Rasa they have never had a working CI for duckling 😁 )

**Comment by hsm207** [comment]
The build fails on a fork too (see [here](https://github.com/hsm207/duckling/pull/2)).

It fails on a windows build too but for a different package:

image

**Comment by wochinge** [comment]
Can you please tag a new release?

**Comment by hsm207** [comment]
Do we have docs to show how to make a duckling release?

Also, I found that running the build sequentially on my fork makes workflow run to completion. See [this](https://github.com/hsm207/duckling/pull/2/commits/4e7db8b01c1dddc75a08c1316ec8681a648f2f12) commit

**Comment by wochinge** [comment]
I think it's enough to push a tag 🤔 

> Also, I found that running the build sequentially on my fork makes workflow run to completion. See this commit

Mhm, weird 🤷🏻 Maybe create an issue / PR in the upstream repo?

**Comment by hsm207** [comment]
I've tag a new release.

> Mhm, weird 🤷🏻 Maybe create an issue / PR in the upstream repo?

Will do!

**Pull request merged**
