### PR TITLE
Skip logfile creation

### PR DESCRIPTION
**Pull request by wochinge**
**Motivation**
Currently the log files and the log directory for the server are always created, even if the logging is disabled. If duckling is used on OpenShift the file creation leads to errors if no volume mount is defined.

**Proposed Change:**
Only create log files / log directory if the logging is enabled.

Also did a pr at Facebooks repository so that the fork does not diverge to much: https://github.com/facebook/duckling/pull/377

### CODE REVIEW

**Comment by wochinge** [comment]
Any idea why the build is failing?

**Comment by tmbo** [comment]
no, no idea 🤷‍♂  is it failing on the fb repo as well?

**Comment by wochinge** [comment]
Failing for two of three compilers: https://travis-ci.org/facebook/duckling/builds/536734516?utm_source=github_status&utm_medium=notification 

But that's also not my change 😑 , but rather their current master which is the problem.

**Comment by tmbo** [comment]
I mean if the server still starts I am fine with us merging this. we should also update master and pull in latest master from fb. after that we can tag a new version for the docker image.

**Review by tmbo — APPROVED** [review]
looks good I guess 😅

**Comment by wochinge** [comment]
ok. Should I do the merge with latest master?

**Comment by tmbo** [comment]
yes please

**Comment by tmbo** [comment]
Can we merge this?

**Pull request merged**
